### ISSUE TITLE
closeheat.com addres can't be found

### ISSUE THREAD

**Issue by aftarfadilah** [ripienaar/free-for-dev#1014]
The link for closeheat.com is unavailable and will get an error of `ERR_NAME_NOT_RESOLVED`. I tried deleting my cookies but nothing happens.

Perhaps they close the service or change domain? The URL is also rank 1 in google search.

**Comment by aftarfadilah** [comment]
Sure, this will be the second PR after my tutorial PR

**Comment by ripienaar** [comment]
thank you :)
