### ISSUE TITLE
Outdated free tier for Elastic Email

### ISSUE THREAD

**Issue by mpus** [ripienaar/free-for-dev#1018]
Hi, there is outdated info about the free tier for Elastic Email. After the pricing change, you can send 100 free emails per day now.

They offer an unlimited amount of emails for $9 per month where you pay only for the number of contacts you have.

**Comment by ripienaar** [comment]
Would you mind sending a PR to adjust the info here?

**Comment by mpus** [comment]
In that context that we have in this thread, I think that the best information would be:

100 free emails/day. 1,000 emails for $0.09 through API (pay as you go).
