### ISSUE TITLE
Add custom domain to github pages

### ISSUE THREAD

**Issue by C0derLint** [ripienaar/free-for-dev#1038]
I recently happened to see that [js.org](js.org) is offering *.js.org custom domains for projects [here](https://github.com/js-org/js.org). Maybe we could reserve a `freefordev.js.org`?

**Comment by ripienaar** [comment]
It’s not really JS related. Happy how it is.

**Comment by C0derLint** [comment]
Hmmm you make a good point 😂

**Comment by ripienaar** [comment]
It's now on free-for.dev
