### ISSUE TITLE
Codeanywhere: Transition to Free Trial

### ISSUE THREAD

**Issue by zartdinov** [ripienaar/free-for-dev#1041]
>Dear Codeanywhere user,
>
>We are writing this email to inform you that as of March 1st 2019 the Free tier will become a free trial and limited to 7 Days use.
>
>Why are we removing free?
>We at Codeanywhere have always tried to give our customers the best value for their money making sure that we just cover our operating expenses. Lately the increasing demand from our user base to boost the performance of our container service forced us to increase the operating cost of running our service, and with that, a forever for free plan is no longer feasible.
>
>As mentioned earlier and as you all know yourselves, compute power is not cheap, and as a preemptive measure for this we have to scale back on free usage.
>
>What about education use?
>We do offer very large discounts for education use, furthermore if you do decide to upgrade to an Educational licence, only the teacher/admin has to use a Credit Card, students do not have to, so you have no worries there.
>
>What and why now?
We understand that this will be hard on some, and we are very, very sorry for this, we tried to prevent closing free accounts completely, but the economics just did not work out.
>
>We will do our best to help all we can to transition in this period, so please feel to reach out if we can help in any matter or form.
>
>Furthermore this is one of the reasons we have reactivated the lifetime 40% discount, if you upgrade and use the following code (Promo code: ##### valid until 15th March. 2019) you will have a 40% discount on any and all plans for the rest of your life.
>
>We truly hope this is the last of our policy changes for a long, long time, and hope you will support us by upgrading, so we as Codeanywhere can continue on this journey of helping you code, from anywhere.
>
>Thank you for understanding.
>Your Codeanywhere Team.

**Comment by ripienaar** [comment]
joy, want to send a PR and remove them? Thanks!

**Comment by ripienaar** [comment]
thanks a lot!

**Comment by zartdinov** [comment]
Cool repo. Thanks too!
