### ISSUE TITLE
Framasoft

### ISSUE THREAD

**Issue by franky47** [ripienaar/free-for-dev#1049]
A list of free/libre open source SaaS maintained by the [Framasoft](https://framasoft.org) French non-profit can be found here:
https://degooglisons-internet.org/en/list/

**Comment by ripienaar** [comment]
wow this is quite epic, 90% of not suitable for this list, but seems like something worth adding anyway due to the git repo etc.

Wanna do a PR?

**Comment by franky47** [comment]
We can split the services up, which one do you think would fit nicely in the list ? I can do a PR to integrate them.

**Comment by ripienaar** [comment]
it would have bits and pieces that apply to several catagories and i try not to add them to many - so perhaps at the bottom of the list in other free resources?

**Comment by franky47** [comment]
Sure !
