### ISSUE TITLE
Localtunnel to STUN, WebRTC, Web Socket Servers and Other Routers

### ISSUE THREAD

**Issue by miceve** [ripienaar/free-for-dev#1058]
Can localtunnel (https://localtunnel.me) be added to STUN, WebRTC, Web Socket Servers and Other Routers?
It provides a free tunneling service, alternative to ngrok.io. Has many free features whith on ngrok is paid.

**Comment by ripienaar** [comment]
its a bit different than STUN WebRTC though - maybe `Miscellaneous`?

**Comment by aliglelo** [comment]
@rykovnikita its a very good option!Thanks for helping!

**Comment by ripienaar** [comment]
house keeping ancient issues
