### ISSUE TITLE
A new tool 

### ISSUE THREAD

**Issue by MeetChopra** [ripienaar/free-for-dev#1063]
A new tool in monitoring - Freshping.io
Website monitoring tool with 50 checks at 1-min interval and 5 public status pages for free

**Comment by aliglelo** [comment]
Checked it out and I must say an awesome service.
I also think it should be avialable to all.

**Comment by ripienaar** [comment]
send a PR please :)

**Comment by ripienaar** [comment]
house keeping ancient issues
