### ISSUE TITLE
Add https://spectrum.chat/

### ISSUE THREAD

**Issue by AdroitProgrammer** [ripienaar/free-for-dev#1096]
After they were acquired by Github they made all the features for creating communities free. You can read more [here](https://spectrum.chat/spectrum/general/where-is-the-pricing-page~5085e7a2-a898-40cc-bf95-e9c9ef70e27d?m=MTU0NTI0NjIyMzYyNQ==)

**Comment by ripienaar** [comment]
nice, wanna do a PR?

**Comment by AdroitProgrammer** [comment]
Like a personal reference? I am apart of someone else's community on there and it's really dope. If PR means placement request then the Tools for Teams and Collaboration sections seems good. If there was a Community and Support section it could go there.

**Comment by ripienaar** [comment]
A PR as in a GitHub Pull Request that lets you add it yourself :) I get a message saying you want to add it and then accept it - and forever it keeps you as the contributor for that link.

**Comment by AdroitProgrammer** [comment]
Gotcha. I tried it and it wouldn't let me push a commit to do the pull request off of.

**Comment by varesa** [comment]
> Gotcha. I tried it and it wouldn't let me push a commit to do the pull request off of.

You won't be able to push to the ripienaar/free-for-dev repository if that is what you tried. You should make a clone/fork under your own account, push there and then open a pull request for the changes to be included in the main repo
