### ISSUE TITLE
apinf - API Management Platform

### ISSUE THREAD

**Issue by bitsnaps** [ripienaar/free-for-dev#1103]
They provide SaaS cloud platform, price starts from 0$ (for 0 - 30,000 API Requests​)
https://www.apinf.com/api-management-platform
anyone has some experience? what would be the right category?

**Comment by ripienaar** [comment]
not quite a perfect fit but maybe `APIs, Data and ML`? do you want to send a pull request to add it?

**Comment by bitsnaps** [comment]
@ripienaar not quit sure, I need to try it first, I'll PR as soon as I can. Thanks.

**Comment by davidjameshowell** [comment]
Looks like this site does not resolve anymore; directing to a Wix landing page.

**Comment by ripienaar** [comment]
thanks, problem solved :)
