### ISSUE TITLE
WebSite Tools for Free-For-Dev Directory

### ISSUE THREAD

**Issue by TraderStf** [ripienaar/free-for-dev#111]
Hello,

As I make a list/directory of sites, on totally different subjects, I have searched for appropriate tools to easily handle all these links.

Here is what remains on my list until today. I have no link with any of them.

I hope this could help you to do FFD Directory.

Stéphane.

<h3>— Arfoo —</h3>

[Arfooo](http://script.arfooo.net/) is a free and Open Source directory script.

Apache (mod_rewrite)
PHP 5.1
MySQL 4.1
Javascript, jQuery, SPL, Curl, GD, XML
MVC architecture
UTF8 support

[Arfooo 2.0 Features](http://script.arfooo.net/features/)

<h3>— eSyndiCat —</h3>

[eSyndiCat](http://script.arfooo.net/) is directory script available in two versions:
- version 1.7 is free which is maintained and kept up-to-date though with less features.
- version 2.3 is a 75 $USD one time payment for one domain with no hidden fees.

Apache 1.3 (mod_rewrite) or Microsoft IIS (ISAPIRewirite 3)
PHP 5.2
MySQL 4.1
GD, XML, Zlib, Freetype
<i>ionCube loaders will be required for version 3</i>

[eSyndiCat Features and Comparison](http://www.esyndicat.com/product/comparison.html)

<h3>— SMF Forum —</h3>

As I was thinking to list sites but also to let visitors add comments, recommendations, votes... I have also searched for forum / webboard / bulletin board tools.

I have chosen [Simple Machines Forum](http://www.simplemachines.org/) which is neat, powerful not bloated, and very secure.

SMF is free and Open Source.

Apache 2.0 (mod_rewrite) or Microsoft IIS
PHP 5.5
MySQL 4.0.18 / PostgreSQL 8.0 / SQLite 2.x (not 3.)

[SMF Features](http://www.simplemachines.org/about/smf/features.php)

**Comment by ripienaar** [comment]
house keeping ancient issues
