### ISSUE TITLE
Add workers.dev

### ISSUE THREAD

**Issue by obezuk** [ripienaar/free-for-dev#1112]
Cloudflare provides 100,000 free serverless executions per day with your own *.workers.dev subdomain. Cloudflare is already listed as a free DNS and CDN/Protection but Workers would be better positioned in the PaaS category. 

https://workers.cloudflare.com

**Comment by ripienaar** [comment]
yup, good fit, want to open a PR?

**Comment by obezuk** [comment]
Sure, see https://github.com/ripienaar/free-for-dev/pull/1114
