### ISSUE TITLE
Add IBM cloud

### ISSUE THREAD

**Issue by biblia19** [ripienaar/free-for-dev#1142]
No credit card needed, and always free services exist.
Link is [here](https://ibm.com/cloud/free/)

**Comment by bitsnaps** [comment]
@biblia19 I've tried to create an account, but since I've already registered at `cloud.ibm.com` so I can't use the same email, and my account cannot be activated because I had to enter a valid credit card.

**Comment by biblia19** [comment]
Some features can use without enter a valid credit card.

**Comment by ripienaar** [comment]
IBM cloud is already added, thanks!
