### ISSUE TITLE
Add sitemonki.com for free website uptime, domain & SSL monitoring. 

### ISSUE THREAD

**Issue by oquidave** [ripienaar/free-for-dev#1148]
Hello [Site Monki](https://sitemonki.com) has forever free package for website uptime, domain and SSL monitoring. This includes 5 websites, 5 domains and 5 SSL certificate hostnames. It's easy to use and very reliable.

**Comment by ripienaar** [comment]
nice, send a PR?

**Comment by oquidave** [comment]
Just did that. Thanks
