### ISSUE TITLE
Please Add Codesolvent

### ISSUE THREAD

**Issue by Devmond** [ripienaar/free-for-dev#1168]
https://codesolvent.com/

It goes under IDE/Code editors

**Comment by ripienaar** [comment]
pls send a PR - its hard to figure out from this site but it would only fit if the whole thing is delivered aaS - ie no self hosting stuff

**Comment by Devmond** [comment]
There is a sign-up link on the home page like any SaaS solution...it is actually more of a PaaS...when you login, you can provision a box with the software running on it. There is a free trial.

**Comment by ripienaar** [comment]
How long is the trial? Needs to be at least a year. Anyway if this isn’t easily verifiable on the actual site I can’t add it. We don’t ha e for all the digging to verify validity. Transparency matters to our ability to maintain this list

**Comment by Devmond** [comment]
@ripienaar I seem to be missing something here. There is a signup link like any other SaaS/PaaS out there, you login and see what you have access to...what am I missing regarding transparency? 

The trial is not time based per say, you get 24 hours of compute cycle to try the software with all its features, you can shutdown the instance when not in use to preserve the duration of your trial period for as long as you want.

**Comment by ripienaar** [comment]
The details of the trial is not visible WITHOUT signing up. Can you imagine if I had to sign up for each of the 543 services on this list to verify their offerings? And then so would every other person who help maintain this list have to do the same?

The list simply would not exist. If we accept such services.  So I cannot see the details of what they offer on their site without signing up, so I am not adding it to the list.

Thanks

**Comment by Devmond** [comment]
@ripienaar I am having a really hard time seeing how for instance https://www.gitpod.io/ (which is listed) is different from what you get from the codesolvent site.  

The product's documentation is linked right on the home page for anyone who wants to know what it is. There are video screencasts, again all on the site.

It says create a free account, again on the home page, which implies free trial at a minimum.

 It seems you're simply selecting for what you're already predisposed to liking..that is ok:)

**Comment by ripienaar** [comment]
I have to know the TERMS OF THE FREE TRIAL. Saying "there is a free trial" does not help me.

Lets compare with gitpod, it's clear as day no doubt at all what is free and I can get the information I need to maintain the list in about 2 seconds:

![gitpod](https://i.imgur.com/plPxk8d.png)

Here is codesolvent `<blank>` cos nowhere is there any details at all about what the free trial means or gives one.

Here is a quote from the top of the README:

```
NOTE: This list is only for as-a-Service offerings, not for self-hosted software. For a service to be eligible it has to offer a Free Tier and not just a free trial. If the Free Tier is time bucketed it has to be at least a year.
```

So I ask to see in clear details on the service if it complies with this, thats all.

I am not predisposed to anything, there are nearly 500 entries on the list I assure you I do not have oppinions about most of them.  I am only predisposed to those that comply with the rules of the list and who makes it easy for me to review them.
