### ISSUE TITLE
Add https://reqbin.com/. 

### ISSUE THREAD

**Issue by JoeyEamigh** [ripienaar/free-for-dev#1224]
https://reqbin.com/ 

This is a misc. free service for POST, GET, PUT, HEAD, DELETE, and OPTIONS support. Includes headers and authentication support, as well as payload obviously. Always free and amazing for testing your code without having to trigger the actual event.

**Comment by ripienaar** [comment]
nice, want to send a PR to add it?

**Comment by ripienaar** [comment]
Ah I missed that you did send one :) good stuff thank you
