### ISSUE TITLE
add new web hostings

### ISSUE THREAD

**Issue by matheusfelipeog** [ripienaar/free-for-dev#1235]
New Hostings for a Web Hostings Session. Can i send a PR?

- [Infinity Free](https://infinityfree.net/) - Completely free website hosting with unlimited disk space and bandwidth.

- [000WebHost](https://www.000webhost.com/) - Zero cost website hosting with PHP, MySQL, cPanel & no ads!

- [Free Host](https://profreehost.com/login/) - Free Web Hosting with Unlimited diskspace and bandwidth.

- [Free Hosting](http://freehostingnoads.net/) - Free HostingWith PHP 5, Perl, CGI, MySQL, FTP, File Manager, POP E-Mail, free sub-domains, free domain hosting, DNS Zone Editor, Web Site Statistics, FREE Online Support and many more features not offered by other free hosts.

**Comment by ripienaar** [comment]
yup, send a PR thanks
