### ISSUE TITLE
zoho.com is now webmail only

### ISSUE THREAD

**Issue by iandstanley** [ripienaar/free-for-dev#1294]
free email for upto 5 users is now webmail only for zoho
https://www.zoho.com/mail/zohomail-pricing.html

normal email access (smtp/imap/pop3) is charged

**Comment by ripienaar** [comment]
thanks, do you want to send a PR to adjust it?

**Comment by davidgeary** [comment]
@iandstanley Are you sure SMTP, etc, is charged for? I know that that's what the pricing page suggests, but I'm currently on the 'Mail Free' plan and using POP3, IMAP and SMTP on various devices without any problems.

(Of course, it's possible that my 'Mail Free' plan is an old plan that's been grandfathered, while the 'Forever Free' plan on the pricing page is now the current offering for new accounts.)

**Comment by iandstanley** [comment]
> @iandstanley Are you sure SMTP, etc, is charged for? I know that that's what the pricing page suggests, but I'm currently on the 'Mail Free' plan and using POP3, IMAP and SMTP on various devices without any problems.
> 
> (Of course, it's possible that my 'Mail Free' plan is an old plan that's been grandfathered, while the 'Forever Free' plan on the pricing page is now the current offering for new accounts.)



Yes 

Forever free is only webmail  .... see this link

https://www.zoho.com/mail/zohomail-pricing.html?src=zmail


It is a relatively recent change and has caused quite a stir on the help forums 

https://help.zoho.com/portal/community/topic/no-more-imap-pop-smtp-on-free-plans-even-on-referrals-with-no-notice

**Comment by iandstanley** [comment]
The pricing page offers three paid plans which have client access

**Comment by murarisumit** [comment]
@davidgeary even I am using it for free. 

AFAIK people with older account can continue with their free IMAP and POP3, but for new customers it is only webmail as @iandstanley said

**Comment by ripienaar** [comment]
thanks for the comments and PR, we'll go with webmail only for now, once they make their offerings clearer and the guess work can stop we can always fix it, for now it says webmail :)

**Comment by davidgeary** [comment]
Thanks for the link @iandstanley - good to know (thought the change of plan name might be significant).
