### ISSUE TITLE
dbdesigner.net cloud-based database modeling

### ISSUE THREAD

**Issue by bitsnaps** [ripienaar/free-for-dev#1300]
This service dbdesigner.net is online database schema design and modeling tool, their provide a free tiers with 2 Database Models and 10 Tables per Model, what would be the best category for that?

**Comment by ripienaar** [comment]
Doesnt appear to be any *good* matches, but *APIs, Data and ML* is probably closest.

**Comment by bitsnaps** [comment]
Seems a good fit, here you are https://github.com/ripienaar/free-for-dev/pull/1301

**Comment by ripienaar** [comment]
thank you :)
