### ISSUE TITLE
Add AccessLint tool in CI/CD section

### ISSUE THREAD

**Issue by cankush625** [ripienaar/free-for-dev#1309]
**AccessLint** - Find accessibility issues in your pull requests

AccessLint brings automated web accessibility testing into your development workflow. When a pull request is opened, AccessLint reviews the changes and comments with any new accessibility issues, giving you quick, timely, and targeted feedback, before code goes live.

View the tool here - [AccessLint](https://github.com/marketplace/accesslint)

**Comment by ripienaar** [comment]
Nice. Want to send a PR?

**Comment by cankush625** [comment]
@ripienaar Yes. I will send it

**Comment by cankush625** [comment]
Closing this issue because AccessLint tool is added
