### ISSUE TITLE
Add Imgbot app in Code Quality section

### ISSUE THREAD

**Issue by cankush625** [ripienaar/free-for-dev#1310]
**Imgbot** - Optimises image

Imgbot is a friendly robot that optimizes your images and saves you time. Optimized images mean smaller file sizes without sacrificing quality.

Shortly after installing Imgbot, you will receive a pull request with all of your images optimized. Just merge the pull request and you’re done! As you work on your project, Imgbot works alongside you to keep your images optimized.

Imgbot uses lossless compression by default.

View the app here [Imgbot](https://github.com/marketplace/imgbot)

It's very useful for web developers and increases page response time.

**Comment by ripienaar** [comment]
Thanks. Want to send a PR?

**Comment by cankush625** [comment]
@ripienaar Yes. I will send it.

**Comment by cankush625** [comment]
Closing this issue because Imgbot app is added
