### ISSUE TITLE
Add speed testing sites to 

### ISSUE THREAD

**Issue by tcope25** [ripienaar/free-for-dev#1362]
Add site speed testing tools to the "testing" section:

Pingdom - Monitor your website's availability and performance for free with Pingdom and always be the first to know when your website is down.
Pagespeed Insights - PageSpeed Insights analyzes the content of a web page, then generates suggestions to make that page faster.
Speedmonitor.io - Track your website speed and performance data every day and track performance over time.
Webpagetest.org - Test your site speed from servers around the world.

**Comment by ripienaar** [comment]
Please send a PR

**Comment by tcope25** [comment]
done

**Comment by tcope25** [comment]
#1364
