### ISSUE TITLE
IDE and Code Editing

### ISSUE THREAD

**Issue by luizbills** [ripienaar/free-for-dev#190]
http://codio.com

**Comment by ripienaar** [comment]
do you mind making a PR?

**Comment by steelbrain** [comment]
Would love to see Atom there, and I would love it even more to send a PR, but my schedule doesn't allow me

**Comment by ripienaar** [comment]
The list isn't really for downloadable tools. It's for *aaS so I don't think it would fit 

---
R.I.Pienaar

**Comment by steelbrain** [comment]
@ripienaar I saw the JetBrains products there, and they don't really fit in *aaS

**Comment by ripienaar** [comment]
Indeed, though there are not entries specific to the downloadable IDEs but ones that lists them along with the hosted services thats a closer fit for the list.  PRs for just the IDEs didnt make it in either :)
