### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by bucaran** [ripienaar/free-for-dev#199]
@ripienaar Hi!

We are creating a [GitHub Organization](https://github.com/AwesomeOpenSource) for all awesome open source repos. We are working with a few individuals who are also managing their own awesome repos, and we think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. 

What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by ripienaar** [comment]
these are not opensource, almost none of them are.

**Comment by bucaran** [comment]
@ripienaar I mean, your list.

**Comment by ripienaar** [comment]
no don't think I'd be keen

**Comment by bucaran** [comment]
That's too bad, but thanks anyway. :+1:
