### ISSUE TITLE
Huge List of Sites to Check...

### ISSUE THREAD

**Issue by TraderStf** [ripienaar/free-for-dev#215]
Hello Guys,

I have no more time to check all these.

NOTE - it is NOT the site below but on the pages listed below, they mention hundreds of tools, services with which their own tools can work...

You need to check alllll these tools listed in these pages like I used to do for previous/already listed in FFD.

Good luck 😰

Stf

https://zapier.com/status/
http://clicky.com/help/pricing and also http://clicky.com/compare/
http://www.freshbooks.com/addons
https://www.sumologic.com/partners/
http://www.appdynamics.com/product/extensibility/

**Comment by TraderStf** [comment]
https://blackfire.io/partners

**Comment by Reubend** [comment]
Thanks for these. I might look through them and add some stuff.

**Comment by Waterloo** [comment]
Thank You @TraderStf

**Comment by TraderStf** [comment]
Here we go for a huge one:
https://elements.heroku.com/addons

**Comment by TraderStf** [comment]
https://console.ng.bluemix.net/catalog/

**Comment by TraderStf** [comment]
A bit more......... 10 Trillion $ for the first which check them all...

https://ifttt.com/channels

**Comment by TraderStf** [comment]
Here we go again:
https://slack.com/apps

**Comment by TraderStf** [comment]
TODO LATER for myself: fonticons.com NOW fortawesome.com

**Comment by TraderStf** [comment]
http://fontawesome.io/icons/
chapter BRANDS, if listed, must be famous... blabla

**Comment by TraderStf** [comment]
@ripienaar look who's listed ! http://www.bypeople.com/web-development-tools/

**Comment by ripienaar** [comment]
@TraderStf hehe nice

**Comment by TraderStf** [comment]
https://stackpile.io/apps

**Comment by TraderStf** [comment]
Few hundreds more...
https://botlist.co

anyone to handle this slave work?

**Comment by TraderStf** [comment]
One intruders inside that big list
https://bubble.is/plugins

**Comment by TraderStf** [comment]
https://madmimi.com/service_agreements/choose_plan
but I am not sure I want to mention a service of godaddy as they do nothing against spammers... see knujon and spamcop, just like ovh btw... how to become rich...

**Comment by ripienaar** [comment]
yeah agree, no thanks for godaddy

**Comment by TraderStf** [comment]
grand'pa should do everything... what's that...

**Comment by ripienaar** [comment]
house keeping ancient issues
