### ISSUE TITLE
http://web.wurfl.io

### ISSUE THREAD

**Issue by TraderStf** [ripienaar/free-for-dev#267]
Free but commercial

don't know if you take this kind and... in what sections :-)

WURFL.js is a JavaScript file that provides information about the device that is accesing your page. Whether it is a desktop browser, a tablet, a mobile phone, a smart TV, game console or someone with his wristwatch.

**Comment by ripienaar** [comment]
hmm, yeah i dont think its something for this list - being focussed on infradev/devops people, I've used wurfl before but not sure how it would fit in the focus of the list
