### ISSUE TITLE
Github Student

### ISSUE THREAD

**Issue by yorickdewid** [ripienaar/free-for-dev#27]
Don't forget about [Github Student pack](https://education.github.com/pack). Very useful for students, and includes a list of potential (free) services.

**Comment by marceloboeira** [comment]
:+1:

**Comment by ripienaar** [comment]
make a PR :) or just mention it along with the existing github link maybe?

**Comment by yorickdewid** [comment]
I would say under __Packs__ or something. I'll make a PR

**Comment by yorickdewid** [comment]
See #30
