### ISSUE TITLE
Pull Mongolab

### ISSUE THREAD

**Issue by kenetik** [ripienaar/free-for-dev#274]
Pulling free services - 

 Dear MongoLab user,

We are writing to inform you that on June 22, 2015 MongoLab will discontinue support for the Joyent cloud. You are receiving this email because you have at least one MongoLab-hosted database running on this cloud provider.

Action is required before June 22

**Comment by ripienaar** [comment]
thanks for this, can you do a PR to remove it?

thanks

**Comment by kenetik** [comment]
Pull request added, would appreciate write permissions.

Regards,

**Comment by ripienaar** [comment]
merged, thanks :)
