### ISSUE TITLE
Add Cloudinary and Incapsula

### ISSUE THREAD

**Issue by nibogd** [ripienaar/free-for-dev#302]
~~[cloudinary](https://cloudinary.com) offers free images CDN with 2GB storage and 5GB bandwidth~~ (Missed that it's already mentioned)
There's also [Incapsula](https://www.incapsula.com/) which offers free cdn and ddos protection, but i failed to add a website (migrate from CloudFlare) :sweat:

**Comment by ripienaar** [comment]
thanks, can you make a PR? that'd be awesome and gets you credit
