### ISSUE TITLE
List of CDNs

### ISSUE THREAD

**Issue by telephone** [ripienaar/free-for-dev#31]
**Assorted CDNs:**

[Bootstrap CDN](http://www.bootstrapcdn.com) - Already listed
[cdnjs](https://cdnjs.com)
[jsDelivr](http://www.jsdelivr.com)

**Javascript CDNs:**

[Google Hosted Libraries](https://developers.google.com/speed/libraries)
[jQuery CDN](https://code.jquery.com)
[​Microsoft Ajax Content Delivery Network](https://www.asp.net/ajax/cdn)
[Yandex CDN](https://tech.yandex.ru/jslibs)

**Comment by ripienaar** [comment]
nice list, want to make a PR?

**Comment by yorickdewid** [comment]
We can list al lot of CDNs but is that the idea ?

**Comment by ripienaar** [comment]
Indeed, I know of a few more too - but when I added the bootstrap one I thought how is it going to be useful for infradev types or devops people (the main audience for this list) and figured a lot of us are bad at web dev and lean hard on bootstrap, so I included that one.

So if others on your list are useful in context and they provide free services lets add them

**Comment by telephone** [comment]
@ripienaar you can just go ahead and commit them, as I'm heading off to bed :sleepy:

In regards to the audience, if you're targeting non-devs and want to keep the list down, sticking to the assorted CDNs would provide the most benefit due to their extensive range of projects.

**Comment by thibmaek** [comment]
surge.sh is also free

**Comment by yorickdewid** [comment]
@thibmaek I believe we are only allowed to propose PR's :laughing:

**Comment by ripienaar** [comment]
Happy to do the leg work and add them myself, but PRs yield quicker outcomes for sure :)

**Comment by TraderStf** [comment]
cloudflare.com - general CDN with extra features, protection, stats,... take a look
