### ISSUE TITLE
Two listings for Analytics

### ISSUE THREAD

**Issue by shakna-israel** [ripienaar/free-for-dev#355]
Analytics hits the list twice:

* [Analytics](https://github.com/ripienaar/free-for-dev#analytics)
* [Analytics, Events and Statistics](https://github.com/ripienaar/free-for-dev#analytics-events-and--statistics)

**Comment by ripienaar** [comment]
thanks for pointing that out, do you want to make a PR to fix? Moving the stuff in the "Analytics" one into the other one seems best.

**Comment by shakna-israel** [comment]
Sure

**Comment by shakna-israel** [comment]
#356 merges them.
