### ISSUE TITLE
scalingo does not have a free tier anymore

### ISSUE THREAD

**Issue by duenni** [ripienaar/free-for-dev#379]
See http://blog.scalingo.com/post/120367616143/upcoming-changes-in-our-pricing-policy

**Comment by ripienaar** [comment]
thanks, do you have a moment to do a PR to remove them?

thanks!

**Comment by duenni** [comment]
Completely remove? They still have a free trial plan..

**Comment by ripienaar** [comment]
Yeah don't really do free trials on the list, one or two on the list but they tend to be really really generous trials like the aws free tier

30 days isn't what this list is for

---
R.I.Pienaar

**Comment by duenni** [comment]
#380
