### ISSUE TITLE
92five for project management

### ISSUE THREAD

**Issue by chintanbanugaria** [ripienaar/free-for-dev#395]
Please add 92five app for project management. http://v1.92fiveapp.com

**Comment by ripienaar** [comment]
this looks really nice and I'm keen to include it just because its so nice, however this list tend to not be for pure self hosted software :( It's for software as a service offerings with free tiers for devs

sorry and thanks for the effort

**Comment by chintanbanugaria** [comment]
No Worries. Thanks.
