### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by arthurvr** [ripienaar/free-for-dev#399]
This repo seems to miss a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by arthurvr** [comment]
@TraderStf Keep in mind that if you haven't selected a license, it basically means the people are not allowed to reproduce, distribute or create derivative works.

**Comment by TraderStf** [comment]
licensesssssss... freedom first... sorry it's another debate between $ and...
I reply this because I have in mind, patent trolls and all other usele$$ vampire$

**Comment by TraderStf** [comment]
![tesla-edi on](https://cloud.githubusercontent.com/assets/5954335/21075863/24d7e900-bf1d-11e6-8ef4-6a8bc8a10a71.jpeg)
