### ISSUE TITLE
API Changelog

### ISSUE THREAD

**Issue by beesofts** [ripienaar/free-for-dev#443]
I've just discovered https://www.apichangelog.com/ which helps devs to watch for apis changes (FB, Twitter, google, etc) but I don't know in which section to put it

**Comment by ripienaar** [comment]
Looks nice, maybe change the "Issue tracking / Project management" to "Issue tracking, Project management and Documentation"?

**Comment by beesofts** [comment]
IMO the best would be to add a new section "technology watch" (translation for french expression "veille technologique")
