### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ShayBox** [ripienaar/free-for-dev#462]
I have a section to add, text editors
Atom.io
Brackets.io
Sublime Text 3
Notepad++

**Comment by ripienaar** [comment]
OK, do you mind sending a PR?

**Comment by merikan** [comment]
Isn't the list just for services (*aaS) or has that changed?

**Comment by ripienaar** [comment]
it's ideally for services only yes, and I think I've probably rejected each of those listed items individually before.

But I am thinking given the developer focussed nature it might be time to add them? Not sure, am on the fence.

**Comment by ShayBox** [comment]
Sorry, this is my first time on github issues, whats a PR?

**Comment by HaMster21** [comment]
A PullRequest :smiley: 

This is also detailed in the GitHub guides [here](https://guides.github.com/introduction/flow/index.html)

**Comment by TraderStf** [comment]
*aas, you can find app store, alternativeto.net, appshopper,...
