### ISSUE TITLE
100$ credit when sign-up for Algorithmia

### ISSUE THREAD

**Issue by TraderStf** [ripienaar/free-for-dev#474]
code: STRATA15
valid until ?

CLICK PROMO CODE Just below password field or it is too late afterwards!

http://blog.algorithmia.com/post/130205532864/algorithmia-wins-the-startup-showcase-at-strata

100$ = 5 x standard package:
5 x  200.000 credits and auto-reload

**Comment by ripienaar** [comment]
not really the kind of promotion i am keen on for this list - have to be something a bit more long term like the aws free year tiers or just outright free for some tier of usage
