### ISSUE TITLE
Add Buddy App

### ISSUE THREAD

**Issue by codecalm** [ripienaar/free-for-dev#494]
Hi, look at https://buddy.works/. I think it would be good in "Source Code Repos" category

**Comment by ripienaar** [comment]
only seems to have a '50 releases' free trial? list is more for software with free tiers

**Comment by codecalm** [comment]
@ripienaar: sure, you can close this issue :)

**Comment by ripienaar** [comment]
thanks for contributing though :) sorry it didnt work out

**Comment by codecalm** [comment]
no problem! ;)
