### ISSUE TITLE
Threat Intelligence Free Solution - Karma

### ISSUE THREAD

**Issue by fportantier** [ripienaar/free-for-dev#522]
Hi,

You can add Karma to your list.

Karma is a free web solution that can be used to add the organization assets (domains, websites, networks, etc), and Karma periodically search this assets on various Threat Intelligence Feeds and reports if any of this assets is listed. 

Also, Karma alerts on bad configurations, like DNS open zone transfers, bad SSL configurations and more.

Link: https://karma.securetia.com

Regards!

**Comment by ripienaar** [comment]
Feel like doing a PR? That tends to be the way things get on the list :)

**Comment by ripienaar** [comment]
house keeping ancient issues
