### ISSUE TITLE
automated/browser testing as it's own section?

### ISSUE THREAD

**Issue by gavinengel** [ripienaar/free-for-dev#523]
You may want to consider automated/browser testing as it's own section.  Here are some:
### automated browser testing
- selenium
- ghostinspector.com
- casper.js
- telerik.com/teststudio
- saucelabs.com/
- loadstorm.com/
- loadimpact.com/
- imacros.net/overview
- nightmare.js

**Comment by cheiff** [comment]
You can add gridlastic.com, too

**Comment by ripienaar** [comment]
A PR would be awesome

**Comment by cheiff** [comment]
#524 
Regards

**Comment by cheiff** [comment]
There seems to be an error with autobuild with
```
Issues :-(
> Links 
1. https://qualys.com/forms/freescan/owasp/ SSL_connect returned=1 errno=0 state=unknown state: tlsv1 unrecognized name
```

**Comment by ripienaar** [comment]
that url doesnt even work in chrome for me - same error, so its probably not good or a issue on their side?

**Comment by ripienaar** [comment]
house keeping ancient issues
