### ISSUE TITLE
Would that fit into 'Issue Tracking and Project Management'

### ISSUE THREAD

**Issue by piccaso** [ripienaar/free-for-dev#555]
Actually its just about estimates:
http://www.planitpoker.com/

Completely free and (IMO) really well done implementation of Planning poker.
You don't even need an account, and it even works on windows phone...
But it's not something i would file under infrastructure for devops like issue tracking.

**Comment by ripienaar** [comment]
Yeah, weird, it might work though, cant harm to add it - it's not something that specifically excludes infra stuff so might be useful to some, want to do a PR?

**Comment by piccaso** [comment]
Has proven very useful for me :)
I'll do a PR
