### ISSUE TITLE
A couple more free Email services

### ISSUE THREAD

**Issue by cdco** [ripienaar/free-for-dev#576]
I found a couple free email services you're missing:

<hr>
- http://maildocker.com/

- 10,000 free emails per month

- Full analytics
<hr>
- https://sendpulse.com/

- 12,000 free emails per month, 50 free emails per hour (15,000 emails per month for mailing lists)
<hr>
- http://www.pepipost.com/

- 25,000 free emails per month (after trial)

- Free unlimited emails for first three months

**Comment by ripienaar** [comment]
do you mind adding a PR for these?

thanks!

**Comment by cdco** [comment]
Done creating PR, https://github.com/ripienaar/free-for-dev/pull/577

**Comment by ripienaar** [comment]
Thank you!
