### ISSUE TITLE
Mailstache unavailable

### ISSUE THREAD

**Issue by chessmango** [ripienaar/free-for-dev#618]
Mailstache (mailstache.io) appears to have no way to sign up for the service, nor any indication that it's usable. The free plan also appears to be 'coming soon'.
Perhaps I'm missing something.

**Comment by ripienaar** [comment]
Maybe a change since being added. Want to do a PR to remove them?

**Comment by bithakr** [comment]
@ripienaar this issue can be closed now, as https://github.com/ripienaar/free-for-dev/pull/651 by ericthorton has already been merged

**Comment by ripienaar** [comment]
thanks! 👍
