### ISSUE TITLE
SourceLair doesn't know what 4ever means :(

### ISSUE THREAD

**Issue by edgardmota** [ripienaar/free-for-dev#619]
As stated at SourceLair blog (https://www.sourcelair.com/blog/articles/100/free-becomes-basic), it seems that they doesn't offer a free forever plan anymore. Now you can only have a free trial for 30 days.

As I wasn't sure if it was the case of removing it, I've opened this issue instead of a PR request.

**Comment by ripienaar** [comment]
I think that is definitely reason to remove them. Want to make a PR?

**Comment by edgardmota** [comment]
Yes, I'll do it, thanks!

**Comment by ripienaar** [comment]
thank you
