### ISSUE TITLE
habitat.sh for package build automation

### ISSUE THREAD

**Issue by SHoar** [ripienaar/free-for-dev#640]
Hi, I just met one of the guys who is working on this, it is all open-source. https://www.habitat.sh. 

I was going to do a PR for Package Build System section to add this in. What do you think?

**Comment by ripienaar** [comment]
this list is for hosted services and while this has a hosted feature in that there's package hosting, so does every other programming language and CM system - way too broad I think

**Comment by ripienaar** [comment]
house keeping ancient issues
