### ISSUE TITLE
Codefresh - Continuous Delivery and Collaboration Platform for Docker uses

### ISSUE THREAD

**Issue by dockermaster** [ripienaar/free-for-dev#649]
Free-for-Life plan: 1 build, 1 environment, shared servers, unlimited public repos

www.codefresh.io

**Comment by ripienaar** [comment]
looks good, can you do a PR please?

thanks!

**Comment by dockermaster** [comment]
Done, can you tell me if I did it correct?

**Comment by ripienaar** [comment]
perfect thank you :)
