### ISSUE TITLE
simplybuilt is not free now?

### ISSUE THREAD

**Issue by yn-coder** [ripienaar/free-for-dev#698]
Hi!

simplybuilt.com has no free plan for opensource now?

http://www.simplybuilt.com/explore/free-websites-for-open-source-projects is 404

How to proof it?

**Comment by ripienaar** [comment]
yup, does seem so, do you want to send a PR to update the doco?

**Comment by yn-coder** [comment]
Simple delete it?

**Comment by ripienaar** [comment]
yup!

**Comment by yn-coder** [comment]
#699
