### ISSUE TITLE
Free SSL

### ISSUE THREAD

**Issue by TraderStf** [ripienaar/free-for-dev#70]
It's not specially for developers, but if you need one for testing or to enhance your SEO (big criteria for google now).
Use it since few months on my site without problem

https://www.startssl.com/?lang=en
offers a 100% free 256-bit SSL Certificate (Class 1), no hidden cost. Web server certificates (SSL/TLS), Client and mail certificates (S/MIME), 128/256-bit encryption, USD 10000 insurance guaranteed, Valid 1 year (365 days) and can be renewed for free.

**Comment by ripienaar** [comment]
this one is on the list already :)

thanks
