### ISSUE TITLE
Sameroom is not free

### ISSUE THREAD

**Issue by logical-and** [ripienaar/free-for-dev#721]

**Comment by ripienaar** [comment]
used to be, these things change, feel like sending a PR?

**Comment by logical-and** [comment]
Free only for first 2 weeks, actually. Then 5 msg/day only (haha), and plans start from $50 (https://sameroom.io/pricing)

**Comment by ripienaar** [comment]
then we should remove it, can you do a PR @logical-and

**Comment by caffeinewriter** [comment]
Looks like #750 closes this out if anyone wants to do that.

**Comment by ripienaar** [comment]
thanks! 👍
