### ISSUE TITLE
What Service do code.visualstudio.com provide?

### ISSUE THREAD

**Issue by imben1109** [ripienaar/free-for-dev#725]
code.visualstudio.com provide the source code and binary of Visual Studio Code. I do not think this provide any service. Or I misunderstand the list or the service provided by the website. Please help to clarify. Thanks.

**Comment by ripienaar** [comment]
yeah I think it should be removed, want to do a PR @imben1109 ?

**Comment by imben1109** [comment]
@ripienaar created a PR. Thanks.

**Comment by ripienaar** [comment]
@imben1109 thanks a lot
