### ISSUE TITLE
Openshift?

### ISSUE THREAD

**Issue by oldshaghat** [ripienaar/free-for-dev#780]
Openshift (Red Hat PaaS) is free (although less so, now with version 3)

**Comment by ripienaar** [comment]
yeah if they have more than a basic free trial or a very good free trial something like the AWS free tier then it would work.

I do seem to recall it being on here and got removed though but not sure right now.  Open a PR lets add it if it has a free tier

**Comment by oldshaghat** [comment]
The new openshift 3 online does have a free tier that advertises itself as 2 pods, some persistent data, with some mandated resource hibernation, but at this point I can't get any of my deployments or any canned examples to actually show up externally (that is, the pods work and exist, but any attempt I make to route to them via the browser fails for reasons I can't determine) so if that turns out to be a consequence of operating in the free tier maybe it makes sense to leave it off the list. Openshift 2 was so much nicer.

**Comment by ripienaar** [comment]
ah thats a shame, well guess then we'll close this one, if you do get things working send a PR :)
