### ISSUE TITLE
Internet.nl - Test for modern Internet Standards like IPv6, DNSSEC, HTTPS, DMARC, STARTTLS and DANE

### ISSUE THREAD

**Issue by baknu** [ripienaar/free-for-dev#822]
Could you add the test website Internet.nl? (The category "Security and PKI" is probably the most logical place.)

# Security and PKI
* [...]
* [Internet.nl](https://internet.nl) — Test for modern Internet Standards like IPv6, DNSSEC, HTTPS, DMARC, STARTTLS and DANE
* [...]

**Comment by ripienaar** [comment]
you can send a PR with the change you wish to make

**Comment by baknu** [comment]
Sure, done: https://github.com/ripienaar/free-for-dev/pull/823
Thanks.

**Comment by ripienaar** [comment]
thanks :)
