### ISSUE TITLE
c9.io is arguably not free any more

### ISSUE THREAD

**Issue by kjhosein** [ripienaar/free-for-dev#830]
AWS acquired them in 2016, and it is now called Cloud9. From what I gather, it's free for use inside AWS, but you still need to pay for whatever underlying EC2 instance and EBS volume you use to run it and store your code.

**Comment by ripienaar** [comment]
want to do a PR to remove it?

**Comment by ripienaar** [comment]
thank you!

**Comment by wintersolutions** [comment]
Thank you for creating this project!
