### ISSUE TITLE
SkySilk Cloud Services

### ISSUE THREAD

**Issue by Kovaelin** [ripienaar/free-for-dev#832]
https://www.skysilk.com/

Has anyone used their service before? They seem to be legit, but the beta will be ending sometime this year. All tiers were free during the beta, and that will be expected to change once released, but it looked like they also provide a regular free tier too.

Credit card verification is required.

**Comment by ripienaar** [comment]
I don’t see any clear indication that there will be a long term free tier. So I can’t really add it as is I think

**Comment by Kovaelin** [comment]
I would recommend you giving it another look. The free tier is long term. All the paid tiers are only free during the beta, which is still currently going.

**Comment by ripienaar** [comment]
@Kovaelin hmm, its not clear to me when the beta ends? or what happens to beta accounts after the beta?

**Comment by Kovaelin** [comment]
The free tier remains free after the beta.

**Comment by ripienaar** [comment]
Where is that written?

**Comment by Kovaelin** [comment]
They've said it on their Twitter before and in e-mails. You can talk to the devs yourself. They've made themselves readily available for questions, if you don't want to take my word for it. I've been using it. I think other people would benefit from it, so I let you know.

**Comment by ripienaar** [comment]
Afraid realistically speaking this list is huge, if I had to reach out to each dev on this list to confirm beta durations and such it would be a full time job.

So I am afraid I have to draw a line with clear information findable on their pricing page, past that I simply couldnt maintain this list effort wise.

Thanks for the submission, but until it's clear to someone visiting their site what the offering is it cannot make it onto the list

**Comment by StevieSiren** [comment]
Hi guys, I'm a tad late to this thread but I actually work for SkySilk.  We plan on launching the platform as soon as possible, and yes we will still have a free VPS option continuing after launch so no need to worry there. If there's anything else I can help with let me know!

**Comment by ripienaar** [comment]
Thanks @StevieSiren, as above, I can only add services where that declaration is clear on their pricing page at the time when I add them.
