### ISSUE TITLE
Remove Telerik Platform - Product is being retired

### ISSUE THREAD

**Issue by maxwellb** [ripienaar/free-for-dev#843]
From https://www.telerik.com/platform-next-level

> As of November 10, 2017, feature development for the product has been discontinued. There will be no new features or product updates. Telerik will continue to support customers during a six-month transition period. Telerik will complete the sunsetting process for Telerik Platform on May 10, 2018.

**Comment by ripienaar** [comment]
hey thanks, feel like sending in a PR?
