### ISSUE TITLE
latlon.io

### ISSUE THREAD

**Issue by cbigart** [ripienaar/free-for-dev#845]
latlon.io — Geocoding API + school districts, census geography divisons and other address based data. 2,500 free requests/month 

Link seems to be broken. Working link below?

https://www.latlong.net/

**Comment by ripienaar** [comment]
Thanks, feel like sending a PR to fix it?

thanks!

**Comment by cbigart** [comment]
Will do, sorry I'm new to Github, still learning!

**Comment by ripienaar** [comment]
@cbigart I think if you just click on the README.md file and click edit it will do it for you :)

**Comment by cbigart** [comment]
Great! Updating
