### ISSUE TITLE
Add google Colab

### ISSUE THREAD

**Issue by JABirchall** [ripienaar/free-for-dev#859]
Google is giving public GPU compute power for research, Great for AI based projects (Currently being by for [Leela Chess Zero](https://github.com/glinscott/leela-chess))

It's a Python notebook environment on a personal VM with an NVIDIA Tesla K80 GPU. Using Colab requires no installation and runs in your browser.

https://colab.research.google.com

**Comment by ripienaar** [comment]
nice, want to make a PR?
