### ISSUE TITLE
Migrate Hasura

### ISSUE THREAD

**Issue by nischkar** [ripienaar/free-for-dev#861]
Hasura should be in the "BaaS" section and not in the "PaaS".

For comparison:
Heroku allows you to upload your files into the server using git and exposing the "worker".
Hasura allows you to create microservices(like heroku's worker), but they have "auth" (authentication), "filestore" (file storage) etc for the backend.

Also according to their documentation, their are more of a "Baas" than a "PaaS" because they encourage to use their own services than using custom ones

**Comment by ripienaar** [comment]
Sounds fair. Want to send a PR?

**Comment by ripienaar** [comment]
thank you!
