### ISSUE TITLE
dependencyci.com seems to have been renamed

### ISSUE THREAD

**Issue by jarikmarwede** [ripienaar/free-for-dev#901]
https://dependencyci.com now redirects to https://tidelift.com.
I am not sure whether they just renamed/rebranded it or whether they completely changed their service.

**Comment by ripienaar** [comment]
suspect its going through a bunch of changes, worth keeping an eye but yeah its not looking great right now

**Comment by ripienaar** [comment]
I'd vote for removing it if you wanted to do a PR

**Comment by jarikmarwede** [comment]
Ok, I will do that
