### ISSUE TITLE
Sumome.com redirects to sumo.com

### ISSUE THREAD

**Issue by jarikmarwede** [ripienaar/free-for-dev#921]
[Sumome.com](https://sumome.com) redirects to [sumo.com](https://sumo.com).
Sumo also offers a free tier but for making email marketing.
I am not sure whether the two are related or sumome.com just got bought by sumo to prevent misspellings.

**Comment by ripienaar** [comment]
pure email marketing anyway doesnt really fit with the scope of the list, so we can kill it

**Comment by jarikmarwede** [comment]
Well, I took another look at it and it seems like it's a collection of tools for marketing that include things like popups, share buttons and so on.
So it could be helpful for developers.
But I don't know.

**Comment by ripienaar** [comment]
yeha bit nebulous for the scope of the list, I'd kill it

**Comment by jarikmarwede** [comment]
Ok, I created a pull request #928
