### ISSUE TITLE
IaaS vs. PaaS

### ISSUE THREAD

**Issue by muminoff** [ripienaar/free-for-dev#94]
Aren't Amazon AWS, Microsoft Azure and HP Cloud IaaS? You classified them PaaS, as Amazon AWS already has Beanstalk as PaaS!

**Comment by ripienaar** [comment]
possibly, for the moment I am just gathering links in rough categories, once I have a big pile of them and a solid idea of the catagories of links I'm going to build a website around this data.  At that point I'll further reconsider the categories and what belongs to what and if a certain link fits the audience I have in mind.

You're probably right but I dont want to fret about it too much just now

**Comment by ripienaar** [comment]
house keeping ancient issues
