### ISSUE TITLE
No free tier on readme.io?

### ISSUE THREAD

**Issue by jarikmarwede** [ripienaar/free-for-dev#953]
I am not able to find a free tier on [readme.io](https://readme.io/).
The only thing I see is a 14 day trial.

**Comment by rvben** [comment]
In the documentation it says they have, but it's not clear from the normal page.
To actually request it, you have to create an account, a project, and you can request the 'open source plan' for that project. Not so straight forward though.

https://readme.readme.io/docs/open-source
