### ISSUE TITLE
Old pricing in list

### ISSUE THREAD

**Issue by jarikmarwede** [ripienaar/free-for-dev#954]
I have noticed that a lot of features that you get with free tiers of the services listed here have changed.
Especially the ones that name specific numbers (like API requests) differ from what is listed here.
It might be good to remove any specific numbers from the list.
But that would make it less easy to scan because you would have to visit each website for details.
I am not sure on this, what do you think?

**Comment by ripienaar** [comment]
yeah its quite difficult, useful given the size of the list to have the info here - but by its nature its never up to date.

I've been thinking about this too - and honestly do not know the right answer :)

**Comment by mberrueta** [comment]
i think that always will be updated by users, that see something useful here, but is not free anymore.
Even out dated is a really nice resource

**Comment by ripienaar** [comment]
yeah, end of the day its a community effort, if its wrong and it bothers them someone will fix it, that's been my approach - though I know that does not lead to actual correctness but its the best we can do I think given the size of the thing

**Comment by jarikmarwede** [comment]
Yeah, for things that are just wrong like services that don't offer a free tier anymore I think people that catch it just have to change it. But I am not sure whether there are enough people that fix smaller things like an API allowing less requests than listed.
