### ISSUE TITLE
Remove newrelic.com

### ISSUE THREAD

**Issue by bazzilio** [ripienaar/free-for-dev#961]
Catalog said:
`newrelic.com — Free with 24 hours data retention`
in realty:
![image](https://user-images.githubusercontent.com/13622424/45518488-5f91f080-b7ba-11e8-8ffa-aeb65b9f3c8d.png)

We should remove newrelic.com  from this catalog

**Comment by ripienaar** [comment]
Used to yeah. Alas. Want to send a PR to remove?

**Comment by bazzilio** [comment]
> Used to yeah. Alas. Want to send a PR to remove?

i would try.
It would be my first PR :)

**Comment by bazzilio** [comment]
Some people may be interested in free APM solution for newrelic

![image](https://user-images.githubusercontent.com/13622424/45520100-805d4480-b7c0-11e8-8988-88c5ae3d6e69.png)

**Comment by ripienaar** [comment]
house keeping ancient issues
