### ISSUE TITLE
Add Dinli

### ISSUE THREAD

**Issue by DiegoRBaquero** [ripienaar/free-for-dev#979]
I built https://din.li/ which is a free URL shortener with a really simple API. 

Also comes with npm package: http://npmjs.com/package/dinli

**Comment by JABirchall** [comment]
I dont class a URL shortener as a developer tool.

**Comment by DiegoRBaquero** [comment]
@JABirchall i.e. email platforms are developer tools then? They are both platforms, accessible through APIs and SDKs for developers.

**Comment by ripienaar** [comment]
yeah if it has a API then its good but on its own I would not be sold on a shortener for this list, feel free to do a PR

**Comment by Paxa** [comment]
SSL certificate already expired

**Comment by ripienaar** [comment]
thanks

**Comment by DiegoRBaquero** [comment]
Yeah, lost the domain to stupid rules from the .li registry and now they are charhing $6500. Thank you though!
