### ISSUE TITLE
Opsgenie recently announced a free tier up to 5 users

### ISSUE THREAD

**Issue by serhatcan** [ripienaar/free-for-dev#999]
I'm not sure which category I should be using, so instead of creating a pull request, I wanted to create an issue. Now you can use Opsgenie for alerting up to 5 users for free. More info available at https://www.opsgenie.com/pricing

**Comment by ripienaar** [comment]
there's a monitoring section, want to send a PR sticking it in there?

**Comment by serhatcan** [comment]
Yeap, will do ASAP. Thank you!
